### ISSUE TITLE
Further Challenges with Champion tracking

### ISSUE THREAD

**Issue by chrisny286** [Nyquase/lol-challenge-tracker#1]
Hey, 
i really like this App. It is exactly what is missing on all of the Challenge Tracker sites out there right now.
Many Challenges which have Champion Tracking are missing though, maybe this is already on your to-do list, if not it would be really cool if you could add them.

Heres a list:

- Perfectionist
- Same penta, Different Champ
- Invincible
- Protean Override
- Master Yourself
- Master the Enemy
- Jack of all Champs

Best regard chrisny

**Comment by Nyquase** [comment]
Hey ! Thanks for your input ! I've just published the latest release with the list you gave me :)
